# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
